# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20160613_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.Company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='utilities',
            field=models.ManyToManyField(to='utilities.Utility'),
        ),
    ]
