# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_auto_20160613_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='utilities',
        ),
        migrations.AddField(
            model_name='utility',
            name='clients',
            field=models.ManyToManyField(to='utilities.Company'),
        ),
    ]
