# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_auto_20160613_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='clients',
        ),
        migrations.AddField(
            model_name='company',
            name='utilities',
            field=models.ManyToManyField(to='utilities.Utility'),
        ),
    ]
