# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0007_auto_20160613_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='utilities',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='utilities',
            field=models.ManyToManyField(blank=True, to='utilities.Utility'),
        ),
        migrations.AlterField(
            model_name='utility',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.Company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='utilities',
            field=models.ManyToManyField(blank=True, to='utilities.Utility'),
        ),
    ]
