# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_auto_20160621_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='users_sort',
            field=models.IntegerField(choices=[(1, 'Alphabetically Sorted'), (-1, 'Alphabetically Sorted Inverted'), (2, 'Login Date Sorted'), (-2, 'Login Date Sorted Inverted'), (3, 'Date Joined Sorted'), (-3, 'Date Joined Sorted Inverted')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='utilities_sort',
            field=models.IntegerField(choices=[(1, 'Alphabetically Sorted'), (-1, 'Alphabetically Sorted Inverted')], default=1),
        ),
    ]
